FROM mattermost/mattermost-enterprise-edition:6.6.1

ENV TZ=UTC
ENV MM_SQLSETTINGS_DRIVERNAME=postgres
ENV MM_SQLSETTINGS_DATASOURCE=${DATABASE_URL}
ENV MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
ENV MM_SERVICESETTINGS_SITEURL=https://${DOMAIN}
